# Generated by Django 5.1.2 on 2024-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='descripcion',
            field=models.CharField(default='proyecto ... ', max_length=100),
        ),
    ]
