# Generated by Django 5.1.2 on 2024-11-17 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spok', '0003_alter_sala_fechaf_alter_sala_fechai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='fechai',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
